# Generated by Django 2.0.10 on 2022-08-28 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0003_invitations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitations',
            new_name='invitation',
        ),
    ]
